# Generated by Django 5.0.2 on 2025-02-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(max_length=255)),
                ('nombre_caracteristica', models.CharField(max_length=255)),
                ('descripcion_caracteristica', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_route', models.CharField(max_length=255)),
                ('name_route', models.CharField(max_length=255)),
                ('distance_route', models.CharField(max_length=100)),
                ('time_travel', models.IntegerField()),
                ('start_time_route', models.DateTimeField()),
                ('end_time_route', models.DateTimeField()),
                ('frequency', models.IntegerField()),
                ('quantity_bus', models.IntegerField()),
                ('description_route', models.TextField()),
                ('barrios', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_route', models.CharField(max_length=255)),
                ('frequency_route', models.IntegerField()),
                ('description_route', models.TextField()),
                ('color_route', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono_app', models.CharField(max_length=255)),
                ('nombre_app', models.CharField(max_length=255)),
                ('descripcion_app', models.TextField()),
                ('caracteristicas_app', models.ManyToManyField(to='Bus.caracteristicaapp')),
            ],
        ),
    ]
