# Generated by Django 5.1.5 on 2025-03-06 22:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appinfo',
            options={'verbose_name': 'Información de la App', 'verbose_name_plural': 'Información de la App'},
        ),
        migrations.AlterModelOptions(
            name='caracteristicaapp',
            options={'verbose_name': 'Característica de la App', 'verbose_name_plural': 'Características de la App'},
        ),
        migrations.AlterModelOptions(
            name='detalleruta',
            options={'verbose_name': 'Detalle de Ruta', 'verbose_name_plural': 'Detalles de Rutas'},
        ),
        migrations.AlterModelOptions(
            name='ruta',
            options={'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='caracteristicas_app',
            field=models.ManyToManyField(to='Bus.caracteristicaapp', verbose_name='Características de la App'),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='descripcion_app',
            field=models.TextField(verbose_name='Descripción de la App'),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='icono_app',
            field=models.ImageField(blank=True, null=True, upload_to='iconos/', verbose_name='Ícono de la App'),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='nombre_app',
            field=models.CharField(max_length=255, verbose_name='Nombre de la App'),
        ),
        migrations.AlterField(
            model_name='caracteristicaapp',
            name='descripcion_caracteristica',
            field=models.TextField(verbose_name='Descripción de la característica'),
        ),
        migrations.AlterField(
            model_name='caracteristicaapp',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='iconos/', verbose_name='Ícono'),
        ),
        migrations.AlterField(
            model_name='caracteristicaapp',
            name='nombre_caracteristica',
            field=models.CharField(max_length=255, verbose_name='Nombre de la característica'),
        ),
        migrations.AlterField(
            model_name='detalleruta',
            name='barrios',
            field=models.JSONField(blank=True, null=True, verbose_name='Lista de Barrios en la Ruta'),
        ),
        migrations.AlterField(
            model_name='detalleruta',
            name='description_route',
            field=models.TextField(verbose_name='Descripción Detallada'),
        ),
        migrations.AlterField(
            model_name='detalleruta',
            name='distance_route',
            field=models.CharField(max_length=100, verbose_name='Distancia de la Ruta'),
        ),
        migrations.AlterField(
            model_name='detalleruta',
            name='end_time_route',
            field=models.DateTimeField(verbose_name='Hora de Finalización'),
        ),
        migrations.AlterField(
            model_name='detalleruta',
            name='frequency',
            field=models.IntegerField(verbose_name='Frecuencia (min)'),
        ),
        migrations.AlterField(
            model_name='detalleruta',
            name='image_route',
            field=models.ImageField(blank=True, null=True, upload_to='rutas/', verbose_name='Imagen de la Ruta'),
        ),
        migrations.AlterField(
            model_name='detalleruta',
            name='name_route',
            field=models.CharField(max_length=255, verbose_name='Nombre de la Ruta'),
        ),
        migrations.AlterField(
            model_name='detalleruta',
            name='quantity_bus',
            field=models.IntegerField(verbose_name='Cantidad de Buses en la Ruta'),
        ),
        migrations.AlterField(
            model_name='detalleruta',
            name='start_time_route',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora de Inicio'),
        ),
        migrations.AlterField(
            model_name='detalleruta',
            name='time_travel',
            field=models.IntegerField(verbose_name='Tiempo Estimado de Viaje (min)'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='color_route',
            field=models.CharField(max_length=7, verbose_name='Color de la Ruta (Hexadecimal)'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='description_route',
            field=models.TextField(verbose_name='Descripción de la Ruta'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='frequency_route',
            field=models.IntegerField(verbose_name='Frecuencia de la Ruta (min)'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='name_route',
            field=models.CharField(max_length=255, verbose_name='Nombre de la Ruta'),
        ),
    ]
