on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH and Deploy
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            cd /home/ubuntu/STP-Villavo
            git pull origin main
            docker-compose down
            docker-compose up --build -d
            docker system prune -f
            docker exec django_app python manage.py makemigrations
            docker exec django_app python manage.py migrate
            docker exec django_app python manage.py collectstatic --noinput
            docker restart django_app
          EOF

          rm -f private_key.pem
